# Generated by Django 3.2.9 on 2022-03-06 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ulid.api.api
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=32, verbose_name='法人名称')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='本社所在地')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='電話番号')),
            ],
            options={
                'verbose_name': '企業ユーザー',
                'verbose_name_plural': '企業ユーザー',
                'db_table': 'company_user',
            },
        ),
        migrations.CreateModel(
            name='JobTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=64, verbose_name='職種')),
            ],
            options={
                'verbose_name': '職種',
                'verbose_name_plural': '職種',
                'db_table': 'job_type',
            },
        ),
        migrations.CreateModel(
            name='LocationUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64, verbose_name='都道府県')),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
                'db_table': 'location_user',
            },
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('pr_message', models.TextField(blank=True, max_length=500, null=True, verbose_name='ひと言PR')),
                ('favorite_thing', models.TextField(blank=True, max_length=500, null=True, verbose_name='好きなことは？')),
                ('status', models.IntegerField(blank=True, default=0, verbose_name='ステータス')),
                ('image_top', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像１')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像3')),
                ('name_kanji', models.CharField(max_length=32, verbose_name='フルネーム（漢字）')),
                ('name_kana', models.CharField(max_length=32, verbose_name='フルネーム（かな）')),
                ('birthdate', models.DateTimeField(verbose_name='生年月日')),
                ('gender', models.IntegerField(verbose_name='性別')),
                ('currently_job', models.CharField(max_length=100, verbose_name='現在の職業')),
                ('education_year', models.DateTimeField(verbose_name='学歴_年')),
                ('education_status', models.IntegerField(default=0, verbose_name='学歴_ステータス')),
                ('school_name', models.CharField(max_length=32, verbose_name='学校名')),
                ('school_type', models.IntegerField(default=0, verbose_name='学歴_学校種類')),
                ('school_department', models.CharField(blank=True, max_length=32, null=True, verbose_name='学部名')),
                ('change_job_time', models.DateTimeField(blank=True, null=True, verbose_name='希望入社時期')),
                ('job_experience1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_experience1', to='users.jobtypemodel', verbose_name='経験職種1')),
                ('job_experience2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_experience2', to='users.jobtypemodel', verbose_name='経験職種2')),
                ('job_experience3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_experience3', to='users.jobtypemodel', verbose_name='経験職種3')),
                ('location1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='location1', to='users.locationusermodel', verbose_name='希望勤務地1')),
                ('location2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='location2', to='users.locationusermodel', verbose_name='希望勤務地2')),
                ('location3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='location3', to='users.locationusermodel', verbose_name='希望勤務地3')),
            ],
            options={
                'verbose_name': '一般ユーザー',
                'verbose_name_plural': '一般ユーザー',
                'db_table': 'normal_user',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='ユーザーネーム')),
                ('user_type', models.IntegerField(default=0, verbose_name='ユーザータイプ')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company_user', models.ForeignKey(blank=True, db_column='company_user_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companyuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('normal_user', models.ForeignKey(blank=True, db_column='normal_user_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.normaluser')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ログイン用共通ユーザー',
                'verbose_name_plural': 'ログイン用共通ユーザー',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
