# Generated by Django 3.2.9 on 2022-03-09 00:27

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='currently_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='現在の職業'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='education_status',
            field=models.IntegerField(blank=True, default=0, verbose_name='学歴_ステータス'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='education_year',
            field=models.DateTimeField(blank=True, null=True, verbose_name='学歴_年'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='gender',
            field=models.IntegerField(blank=True, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='job_experience1',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_experience1', to='users.jobtypemodel', verbose_name='経験職種1'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='job_experience2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_experience2', to='users.jobtypemodel', verbose_name='経験職種2'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='job_experience3',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_experience3', to='users.jobtypemodel', verbose_name='経験職種3'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='location1',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='location1', to='users.locationusermodel', verbose_name='希望勤務地1'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='location2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='location2', to='users.locationusermodel', verbose_name='希望勤務地2'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='location3',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='location3', to='users.locationusermodel', verbose_name='希望勤務地3'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='name_kana',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='フルネーム（かな）'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='name_kanji',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='フルネーム（漢字）'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='school_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='学校名'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='school_type',
            field=models.IntegerField(blank=True, default=0, verbose_name='学歴_学校種類'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
