# Generated by Django 3.2.9 on 2022-03-18 19:56

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220318_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='education_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='学歴_月'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='education_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='学歴_年'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
