# Generated by Django 3.2.9 on 2022-03-19 00:05

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220318_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='job_experience_year1',
            field=models.IntegerField(blank=True, default=0, verbose_name='経験年数1'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='job_experience_year2',
            field=models.IntegerField(blank=True, default=0, verbose_name='経験年数2'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='job_experience_year3',
            field=models.IntegerField(blank=True, default=0, verbose_name='経験年数3'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
