# Generated by Django 3.2.9 on 2021-12-13 12:59

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211213_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_user',
            field=models.ForeignKey(blank=True, db_column='company_user_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companyuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='normal_user',
            field=models.ForeignKey(blank=True, db_column='normal_user_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.normaluser'),
        ),
    ]
