# Generated by Django 3.2.9 on 2022-06-03 21:07

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220326_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='name_kana',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='フルネーム（かな）'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='name_kanji',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='フルネーム（漢字）'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
