# Generated by Django 3.2.9 on 2021-12-13 20:52

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211213_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'verbose_name': '企業ユーザー', 'verbose_name_plural': '企業ユーザー'},
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': '一般ユーザー', 'verbose_name_plural': '一般ユーザー'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ログイン用共通ユーザー', 'verbose_name_plural': 'ログイン用共通ユーザー'},
        ),
        migrations.RenameField(
            model_name='companyuser',
            old_name='nickname',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
