# Generated by Django 3.2.9 on 2022-02-25 23:15

from django.db import migrations, models
import django.utils.timezone
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20220225_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='生年月日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaluser',
            name='currently_job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='現在の職業'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='favorite_thing',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='好きなことは？'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像１'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像2'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像3'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='image_top',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='name_kana',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='フルネーム（かな）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaluser',
            name='name_kanji',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='フルネーム（漢字）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaluser',
            name='pr_message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='ひと言PR'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='status',
            field=models.IntegerField(blank=True, default=0, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='gender',
            field=models.IntegerField(verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
