# Generated by Django 3.2.9 on 2022-03-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=64, verbose_name='業界')),
            ],
            options={
                'verbose_name': '業界',
                'verbose_name_plural': '業界',
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64, verbose_name='地域')),
            ],
            options={
                'verbose_name': '地域',
                'verbose_name_plural': '地域',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='SectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=64, verbose_name='業種')),
            ],
            options={
                'verbose_name': '業種',
                'verbose_name_plural': '業種',
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='WantedTalentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.CharField(max_length=64, verbose_name='人材条件')),
            ],
            options={
                'verbose_name': '人材条件',
                'verbose_name_plural': '人材条件',
                'db_table': 'WantedTalent',
            },
        ),
    ]
