# Generated by Django 3.2.9 on 2022-03-06 18:18

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=64, verbose_name='業界')),
            ],
            options={
                'verbose_name': '業界',
                'verbose_name_plural': '業界',
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='求人題名')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='求人題名補助短文')),
                ('description', models.TextField(blank=True, null=True, verbose_name='仕事内容')),
                ('feature_flag', models.IntegerField(default=0, verbose_name='おすすめ求人フラグ')),
                ('employment_status', models.CharField(blank=True, max_length=64, null=True, verbose_name='雇用形態')),
                ('salary', models.CharField(blank=True, max_length=125, null=True, verbose_name='給料')),
                ('working_hours', models.CharField(blank=True, max_length=125, null=True, verbose_name='勤務時間')),
                ('holidays', models.CharField(blank=True, max_length=256, null=True, verbose_name='休日・休暇')),
                ('welfare', models.TextField(blank=True, null=True, verbose_name='待遇・福利厚生')),
                ('image1', models.ImageField(blank=True, default='images/default.jpeg', null=True, upload_to='images', verbose_name='画像1')),
                ('image2', models.ImageField(blank=True, default='images/default.jpeg', null=True, upload_to='images', verbose_name='画像2')),
                ('image3', models.ImageField(blank=True, default='images/default.jpeg', null=True, upload_to='images', verbose_name='画像3')),
                ('number_hired', models.CharField(blank=True, max_length=125, null=True, verbose_name='採用人数')),
                ('selection', models.TextField(blank=True, null=True, verbose_name='選考内容')),
                ('closing_date', models.CharField(blank=True, max_length=125, null=True, verbose_name='応募締切')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
            ],
            options={
                'verbose_name': '求人',
                'verbose_name_plural': '求人',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64, verbose_name='地域')),
            ],
            options={
                'verbose_name': '地域',
                'verbose_name_plural': '地域',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='SectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=64, verbose_name='業種')),
            ],
            options={
                'verbose_name': '業種',
                'verbose_name_plural': '業種',
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='WantedTalentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.CharField(max_length=64, verbose_name='人材条件')),
            ],
            options={
                'verbose_name': '人材条件',
                'verbose_name_plural': '人材条件',
                'db_table': 'WantedTalent',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteItemModel',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('delete_flg', models.IntegerField(blank=True, default=0, verbose_name='削除フラグ')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='recruit.itemmodel')),
            ],
            options={
                'verbose_name': '求職者から求人へのいいね',
                'verbose_name_plural': '求職者から求人へのいいね',
                'db_table': 'user_favorite_item',
            },
        ),
    ]
