# Generated by Django 3.2.9 on 2022-03-06 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoriteitemmodel',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='users.companyuser', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='industry',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recruit.industrymodel', verbose_name='業界'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='location',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recruit.locationmodel', verbose_name='勤務地'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='sector',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recruit.sectormodel', verbose_name='職種'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='wanted_talent',
            field=models.ManyToManyField(blank=True, to='recruit.WantedTalentModel', verbose_name='求めている人材'),
        ),
    ]
