# Generated by Django 3.2.9 on 2022-03-19 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220319_2053'),
        ('recruit', '0007_auto_20220319_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoriteitemmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='userfavoriteitemmodel',
            name='normal_user',
            field=models.ForeignKey(db_column='normal_user_id', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='users.normaluser', verbose_name='求職者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='recruit.itemmodel', verbose_name='求人'),
        ),
        migrations.CreateModel(
            name='ComFavoriteUserModel',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('delete_flg', models.IntegerField(blank=True, default=0, verbose_name='削除フラグ')),
                ('com_user', models.ForeignKey(db_column='com_user_id', on_delete=django.db.models.deletion.CASCADE, to='users.companyuser', verbose_name='企業')),
                ('normal_user', models.ForeignKey(db_column='normal_user_id', on_delete=django.db.models.deletion.CASCADE, to='users.normaluser', verbose_name='求職者')),
            ],
            options={
                'verbose_name': '企業から求職者へのいいね',
                'verbose_name_plural': '企業から求職者へのいいね',
                'db_table': 'com_favorite_user',
            },
        ),
    ]
