# Generated by Django 3.2.9 on 2022-03-26 14:17

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220326_1417'),
        ('recruit', '0009_auto_20220321_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrmodel',
            name='com_last_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='企業最終確認日時'),
        ),
        migrations.AddField(
            model_name='matchingrmodel',
            name='normal_last_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='求職者最終確認日時'),
        ),
        migrations.AlterField(
            model_name='comfavoriteusermodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchingrmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ChatMessageModel',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('from_user', models.IntegerField(verbose_name='送信者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('delete_flg', models.IntegerField(blank=True, default=0, verbose_name='削除フラグ')),
                ('com_user', models.ForeignKey(db_column='com_user_id', on_delete=django.db.models.deletion.CASCADE, to='users.companyuser', verbose_name='企業')),
                ('normal_user', models.ForeignKey(db_column='normal_user_id', on_delete=django.db.models.deletion.CASCADE, to='users.normaluser', verbose_name='求職者')),
            ],
            options={
                'verbose_name': 'チャットメッセージ',
                'verbose_name_plural': 'チャットメッセージ',
                'db_table': 'chat_message',
            },
        ),
    ]
