# Generated by Django 3.2.9 on 2022-01-18 20:30

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0016_auto_20220118_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'verbose_name': '求人', 'verbose_name_plural': '求人'},
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='求人題名補助短文'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
