# Generated by Django 3.2.9 on 2022-01-18 21:24

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0017_auto_20220118_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavoriteitemmodel',
            options={'verbose_name': '求職者から求人へのいいね', 'verbose_name_plural': '求職者から求人へのいいね'},
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
