# Generated by Django 3.2.9 on 2022-01-18 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220118_2210'),
        ('recruit', '0020_auto_20220118_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='company',
            field=models.ForeignKey(db_column='company_id', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='users.companyuser', verbose_name='企業'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='仕事の概要'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='location',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recruit.locationmodel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
