# Generated by Django 3.2.9 on 2022-01-19 01:10

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0023_auto_20220118_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=64, verbose_name='業界')),
            ],
            options={
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='SectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=64, verbose_name='業種')),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='employment_status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='雇用形態'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='feature_flag',
            field=models.IntegerField(default=0, verbose_name='おすすめ求人フラグ'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='給料'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='仕事内容'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='location',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recruit.locationmodel', verbose_name='勤務地'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='求人題名補助短文'),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
