# Generated by Django 3.2.9 on 2022-01-19 01:13

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0025_auto_20220119_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='industry',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recruit.industrymodel', verbose_name='業界'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='sector',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recruit.sectormodel', verbose_name='職種'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
