# Generated by Django 3.2.9 on 2022-02-06 19:28

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0029_auto_20220122_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedTalentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.CharField(max_length=64, verbose_name='人材条件')),
            ],
            options={
                'db_table': 'WantedTalent',
            },
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='holidays',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='休日・休暇'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='number_hired',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='採用人数'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='selection',
            field=models.TextField(blank=True, null=True, verbose_name='選考内容'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='working_hours',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='勤務時間'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='salary',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='給料'),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
