# Generated by Django 3.2.9 on 2022-02-17 23:27

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20220217_2327'),
        ('recruit', '0030_auto_20220206_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='closing_date',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='応募締切'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='wanted_talent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recruit.wantedtalentmodel', verbose_name='求めている人材'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.companyuser', verbose_name='企業'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
