# Generated by Django 3.2.9 on 2022-02-23 19:26

from django.db import migrations, models
import django.db.models.deletion
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20220223_1926'),
        ('recruit', '0031_auto_20220217_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像１'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='users.companyuser', verbose_name='企業'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
