# Generated by Django 3.2.9 on 2022-02-23 20:46

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0033_auto_20220223_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='welfare',
            field=models.TextField(blank=True, null=True, verbose_name='待遇・福利厚生'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
