# Generated by Django 3.2.9 on 2022-02-25 16:05

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0034_auto_20220223_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='wanted_talent',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='wanted_talent',
            field=models.ManyToManyField(blank=True, to='recruit.WantedTalentModel', verbose_name='求めている人材'),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
