# Generated by Django 3.2.9 on 2022-02-25 16:14

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0035_auto_20220225_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrymodel',
            options={'verbose_name': '業界', 'verbose_name_plural': '業界'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': '地域', 'verbose_name_plural': '地域'},
        ),
        migrations.AlterModelOptions(
            name='sectormodel',
            options={'verbose_name': '業種', 'verbose_name_plural': '業種'},
        ),
        migrations.AlterModelOptions(
            name='wantedtalentmodel',
            options={'verbose_name': '人材条件', 'verbose_name_plural': '人材条件'},
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
