# Generated by Django 3.2.9 on 2022-02-26 00:52

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0038_auto_20220226_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='image2',
            field=models.ImageField(blank=True, default='images/default.jpeg', null=True, upload_to='images', verbose_name='画像2'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='image3',
            field=models.ImageField(blank=True, default='images/default.jpeg', null=True, upload_to='images', verbose_name='画像3'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=125, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='image1',
            field=models.ImageField(blank=True, default='images/default.jpeg', null=True, upload_to='images', verbose_name='画像1'),
        ),
        migrations.AlterField(
            model_name='userfavoriteitemmodel',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
